### ISSUE TITLE
error in dynamic type file loading

### ISSUE THREAD

**Issue by Subham10** [piyasde/minimalweb#1]
I'm getting error "Probably the json variable property declaration are not right
or other Server Error... file path public/home.html server path http://127.0.0.1:3101" when loading a html file first time with format=dynamic and without setting the json variable in the dynamicFileController.

**Comment by piyasde** [comment]
It was previously a bug, now it is a correct behaviour. If someone forget to send any json string, for the routeCollection format "dynamic", the framework will throw the particular error message as shown in response. Someone need to set correct data in controller and need to parse the data properly with ejs templating syntax, as the view is rendered with ejs from the framework.
